In [5]:
# libraries are tensorflow and keras
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
## sentecnes
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am good boy',
      'i am good devloper',
      'understand the meaning of words',
      'your videos are good'
]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'i am good devloper',
 'understand the meaning of words',
 'your videos are good']

In [27]:
# one hot representation
voc_size=10000
onehot_repr=[one_hot(words, voc_size) for words in sent]
onehot_repr

[[197, 458, 3080, 6175],
 [197, 458, 3080, 550],
 [197, 2427, 3080, 3258],
 [7870, 3642, 1243, 5062],
 [7870, 3642, 1243, 5962],
 [2307, 197, 6361, 3080, 6912],
 [4802, 9486, 2183, 1243]]

#  word Embeddings Representation

In [28]:
from tensorflow.keras.layers import Embedding
# pad sequences is used to make the same size of sentences
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [30]:
sent_length=8
#padding=pre means give zeros in front
embedded_docs=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  197  458 3080 6175]
 [   0    0    0    0  197  458 3080  550]
 [   0    0    0    0  197 2427 3080 3258]
 [   0    0    0    0 7870 3642 1243 5062]
 [   0    0    0    0 7870 3642 1243 5962]
 [   0    0    0 2307  197 6361 3080 6912]
 [   0    0    0    0 4802 9486 2183 1243]]


In [31]:
# to pass this in embedding layer we have to specify dimensions
dim=10 # features

In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

D:\Data-Science-Projects\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ Layer (type)          ┃ Output Shape    ┃  Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ embedding_1           │ ?               │        0 │
│ (Embedding)           │                 │ (unbuil… │
└───────────────────────┴─────────────────┴──────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step


array([[[-3.73669043e-02,  8.54729488e-03,  2.30086111e-02,
         -3.22481878e-02, -2.99272183e-02, -5.04553318e-03,
          2.12293603e-02, -4.55563776e-02, -4.57045920e-02,
          1.08579025e-02],
        [-3.73669043e-02,  8.54729488e-03,  2.30086111e-02,
         -3.22481878e-02, -2.99272183e-02, -5.04553318e-03,
          2.12293603e-02, -4.55563776e-02, -4.57045920e-02,
          1.08579025e-02],
        [-3.73669043e-02,  8.54729488e-03,  2.30086111e-02,
         -3.22481878e-02, -2.99272183e-02, -5.04553318e-03,
          2.12293603e-02, -4.55563776e-02, -4.57045920e-02,
          1.08579025e-02],
        [-3.73669043e-02,  8.54729488e-03,  2.30086111e-02,
         -3.22481878e-02, -2.99272183e-02, -5.04553318e-03,
          2.12293603e-02, -4.55563776e-02, -4.57045920e-02,
          1.08579025e-02],
        [ 1.33146532e-02,  3.89975794e-02,  2.48545446e-02,
          4.50422280e-02,  2.63443328e-02,  8.10555369e-03,
         -2.00121291e-02,  2.14497186e-02,  3.601625

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0,  197,  458, 3080, 6175], dtype=int32)

In [38]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
[[-3.73669043e-02  8.54729488e-03  2.30086111e-02 -3.22481878e-02
  -2.99272183e-02 -5.04553318e-03  2.12293603e-02 -4.55563776e-02
  -4.57045920e-02  1.08579025e-02]
 [-3.73669043e-02  8.54729488e-03  2.30086111e-02 -3.22481878e-02
  -2.99272183e-02 -5.04553318e-03  2.12293603e-02 -4.55563776e-02
  -4.57045920e-02  1.08579025e-02]
 [-3.73669043e-02  8.54729488e-03  2.30086111e-02 -3.22481878e-02
  -2.99272183e-02 -5.04553318e-03  2.12293603e-02 -4.55563776e-02
  -4.57045920e-02  1.08579025e-02]
 [-3.73669043e-02  8.54729488e-03  2.30086111e-02 -3.22481878e-02
  -2.99272183e-02 -5.04553318e-03  2.12293603e-02 -4.55563776e-02
  -4.57045920e-02  1.08579025e-02]
 [ 1.33146532e-02  3.89975794e-02  2.48545446e-02  4.50422280e-02
   2.63443328e-02  8.10555369e-03 -2.00121291e-02  2.14497186e-02
   3.60162519e-02  4.70649078e-03]
 [-3.83095630e-02  2.78682150e-02  9.81063768e-03  6.51951879e-03
   3.99411432e-02  2.83839814e-02 -8.63969326e-03 -1.0815657